# Generated by Django 4.2.4 on 2023-09-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['puplish_date']},
        ),
    ]
